version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./project:/project
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py wait_for_db &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A project worker -l info
    volumes:
      - ./project:/project
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - app




  
