# Generated by Django 4.0.4 on 2022-05-17 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tiers',
            field=models.ForeignKey(default=[('Basic', (('name', 'Basic'), ('slug', 'basic'), ('size_thumbnail', '200px')))], on_delete=django.db.models.deletion.CASCADE, to='main.tiers', verbose_name='Tier'),
        ),
    ]
