# Generated by Django 4.0.4 on 2022-05-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customer_tiers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, verbose_name='Size')),
            ],
        ),
        migrations.RemoveField(
            model_name='tiers',
            name='size_thumbnail',
        ),
        migrations.AddField(
            model_name='tiers',
            name='size_thumbnail',
            field=models.ManyToManyField(blank=True, null=True, to='main.size', verbose_name='Size thumbnail'),
        ),
    ]
