# Generated by Django 4.0.4 on 2022-05-17 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_randomurl_slug_randomurl_validity_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randomurl',
            name='validity_url',
        ),
        migrations.AddField(
            model_name='randomurl',
            name='link_expiration_date',
            field=models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(30000)], verbose_name='Link expiration date'),
        ),
    ]
