# Generated by Django 4.0.4 on 2022-05-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_randomurl_url_uploadimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomurl',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/5a41400ea866ad93eb3af076c38913be', max_length=255, verbose_name='Url'),
        ),
    ]
