# Generated by Django 4.0.4 on 2022-05-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_randomurl_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomurl',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/0f66b91ebd6a36b045bb99917b5dab35', max_length=255, verbose_name='Url'),
        ),
    ]
