# Generated by Django 4.0.4 on 2022-05-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_randomurl_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomurl',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/25d6b411c815c01c18b4bd09d2b9e997', max_length=255, verbose_name='Url'),
        ),
    ]
