# Generated by Django 4.0.4 on 2022-05-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_randomurl_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomurl',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/50e0b6cca2007fe806702d382f7f9c84', max_length=255, verbose_name='Url'),
        ),
    ]
