# Generated by Django 4.0.4 on 2022-05-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_randomurl_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomurl',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/5049b31c95ee6099733cc7b4fc10cad8', max_length=255, verbose_name='Url'),
        ),
    ]
