# Generated by Django 4.0.4 on 2022-05-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_randomurl_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomurl',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/db57a577f557ef3d9b8487a7b6e376aa', max_length=255, verbose_name='Url'),
        ),
    ]
