# Generated by Django 4.0.4 on 2022-05-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_randomurl_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomurl',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/57ab53c02e33ff8ee3b7df805e3dd919', max_length=255, verbose_name='Url'),
        ),
    ]
