# Generated by Django 4.0.4 on 2022-05-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_randomurl_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomurl',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/2c650f3dad84afd138198847a23f7c16', max_length=255, verbose_name='Url'),
        ),
    ]
