# Generated by Django 4.0.4 on 2022-05-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_randomurl_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomurl',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/18ce5f3439c9a124d4ac97d0a8d914cf', max_length=255, verbose_name='Url'),
        ),
    ]
