# Generated by Django 4.0.4 on 2022-05-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_randomurl_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomurl',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/93f8f334edf1028301b680bdce8b7b63', max_length=255, verbose_name='Url'),
        ),
    ]
