# Generated by Django 4.0.4 on 2022-05-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_randomurl_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomurl',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/fa5d4d886c4156d85c2bda82da6632a0', max_length=255, verbose_name='Url'),
        ),
    ]
