# Generated by Django 4.0.4 on 2022-05-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_randomurl_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomurl',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/ecfc629e3137626ba403d1ff34e9cc43', max_length=255, verbose_name='Url'),
        ),
    ]
