# Generated by Django 4.0.4 on 2022-05-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_randomurl_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiers',
            name='px',
            field=models.IntegerField(blank=True, null=True, verbose_name='Px'),
        ),
        migrations.AlterField(
            model_name='randomurl',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/1af29612bddc1ba11fa3082e0c81e78a', max_length=255, verbose_name='Url'),
        ),
    ]
