# Generated by Django 4.0.4 on 2022-05-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_tiers_px_alter_randomurl_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiers',
            name='px_two',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Px two'),
        ),
        migrations.AlterField(
            model_name='randomurl',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/7bdf99785fd35d0d542455e01f9b1df6', max_length=255, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='px',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Px'),
        ),
    ]
