# Generated by Django 4.0.4 on 2022-05-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_tiers_px_two_alter_randomurl_url_alter_tiers_px'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomurl',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/e709d02f6da68aaf1e87f4458c2d5359', max_length=255, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(upload_to='img_genre/', verbose_name='Imagine'),
        ),
    ]
