# Generated by Django 4.0.4 on 2022-05-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_randomurl_url_alter_uploadimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomurl',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/8718b98ae3958c41b341cfa771d66d58', max_length=255, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(upload_to='img/', verbose_name='Imagine'),
        ),
    ]
