# Generated by Django 4.0.4 on 2022-05-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_randomurl_url_alter_uploadimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='image_origin_url',
            field=models.ImageField(blank=True, null=True, upload_to='img_origin_url/', verbose_name='Imagine origin url'),
        ),
        migrations.AlterField(
            model_name='randomurl',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/f2eefc4c9ca2fbcc7666b890c413c9aa', max_length=255, verbose_name='Url'),
        ),
    ]
