# Generated by Django 4.0.4 on 2022-05-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_uploadimage_image_origin_url_alter_randomurl_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='image_origin_url',
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='img_thumbnail/', verbose_name='Imagine thumbnail'),
        ),
        migrations.AlterField(
            model_name='randomurl',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/888bb89da5d03f78b1a1df5b3676083e', max_length=255, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(upload_to='img/', verbose_name='Imagine origin url'),
        ),
    ]
