# Generated by Django 4.0.4 on 2022-05-19 14:01

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_remove_uploadimage_image_origin_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='image_thumbnail',
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.image_thumbnail_path, verbose_name='Imagine thumbnail'),
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='thumbnail_image_two',
            field=models.ImageField(blank=True, null=True, upload_to='img_thumbnail_two/', verbose_name='Imagine thumbnail two'),
        ),
        migrations.AlterField(
            model_name='randomurl',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/7eb63562642dcb5a5a0216b91b4b0ae3', max_length=255, verbose_name='Url'),
        ),
    ]
