# Generated by Django 4.0.4 on 2022-05-19 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_remove_uploadimage_image_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomurl',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/ab1b292ebdb8cfebee387f2640dd6258', max_length=255, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='px',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1920)], verbose_name='Px'),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='px_two',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1920)], verbose_name='Px two'),
        ),
    ]
