# Generated by Django 4.0.4 on 2022-05-19 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_randomurl_url_alter_tiers_px_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomurl',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/54a06384cf292f454c8015bb299dd6bc', max_length=255, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='px',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1920)], verbose_name='Px'),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='px_two',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1920)], verbose_name='Px two'),
        ),
    ]
