# Generated by Django 4.0.4 on 2022-05-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_randomurl_url_alter_tiers_px_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomurl',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/3e9d9d0d5c1be208bffa6bf38e6e82b9', max_length=255, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='url_original_image',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=255, null=True, verbose_name='Original image (url)'),
        ),
    ]
