# Generated by Django 4.0.4 on 2022-05-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_randomurl_url_alter_tiers_url_original_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiers',
            old_name='px',
            new_name='size_thumbnail_image',
        ),
        migrations.RenameField(
            model_name='tiers',
            old_name='px_two',
            new_name='size_thumbnail_image_two',
        ),
        migrations.RemoveField(
            model_name='tiers',
            name='size_thumbnail',
        ),
        migrations.AlterField(
            model_name='randomurl',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/6635d43eab16619c53ec286919b92b86', max_length=255, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='url_original_image',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=255, verbose_name='Original image (url)'),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
