# Generated by Django 4.0.4 on 2022-05-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_rename_px_tiers_size_thumbnail_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomurl',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/34652859dc4c8032ed2f2a91250a8c4d', max_length=255, verbose_name='Url'),
        ),
    ]
