# Generated by Django 4.0.4 on 2022-05-19 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_randomurl_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiers',
            name='link_expiration_date',
            field=models.PositiveIntegerField(blank=True, default=300, null=True, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(30000)], verbose_name='Link expiration date'),
        ),
        migrations.AlterField(
            model_name='tiers',
            name='random_expiring_url',
            field=models.CharField(choices=[('None', 'None'), ('http://127.0.0.1:8000/6ff4dc176ad9f6555e3e8bb53ce36478', 'http://127.0.0.1:8000/6ff4dc176ad9f6555e3e8bb53ce36478')], default='None', max_length=255, verbose_name='Random expiring url'),
        ),
        migrations.DeleteModel(
            name='RandomUrl',
        ),
    ]
