# Generated by Django 4.0.4 on 2022-05-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_tiers_link_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiers',
            name='random_expiring_url',
            field=models.CharField(choices=[('None', 'None'), ('http://127.0.0.1:8000/ded6f6fa97e641f18e0e236b88692fe5', 'http://127.0.0.1:8000/ded6f6fa97e641f18e0e236b88692fe5'), ('http://127.0.0.1:8000/47e9eadce7c3b0f7d1cda0be20283ad55fc14eb8', 'http://127.0.0.1:8000/47e9eadce7c3b0f7d1cda0be20283ad55fc14eb8')], default='None', max_length=255, verbose_name='Random expiring url'),
        ),
    ]
