# Generated by Django 4.0.4 on 2022-05-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_tiers_random_expiring_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiers',
            name='random_expiring_url',
            field=models.CharField(choices=[('None', 'None'), ('http://127.0.0.1:8000/cc91737ac7683a07be9335cf3797f6ae', 'http://127.0.0.1:8000/cc91737ac7683a07be9335cf3797f6ae'), ('http://127.0.0.1:8000/7de91636d4b2f829b0bf0ecb04d9ae955964a031', 'http://127.0.0.1:8000/7de91636d4b2f829b0bf0ecb04d9ae955964a031')], default='None', max_length=255, verbose_name='Random expiring url'),
        ),
    ]
