# Generated by Django 4.0.4 on 2022-05-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_alter_tiers_random_expiring_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiers',
            name='random_expiring_url',
            field=models.CharField(choices=[('None', 'None'), ('http://127.0.0.1:8000/4246384c3ead263f59a5e027f81d14ed', 'http://127.0.0.1:8000/4246384c3ead263f59a5e027f81d14ed'), ('http://127.0.0.1:8000/c459113844d4d1300c681eaa1639b6aff110c5a8', 'http://127.0.0.1:8000/c459113844d4d1300c681eaa1639b6aff110c5a8')], default='None', max_length=255, verbose_name='Random expiring url'),
        ),
    ]
