# Generated by Django 4.0.4 on 2022-05-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_alter_tiers_random_expiring_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiers',
            name='random_expiring_url',
            field=models.CharField(choices=[('None', 'None'), ('http://127.0.0.1:8000/45caa022a526c1bfb53a54e082c85391', 'http://127.0.0.1:8000/45caa022a526c1bfb53a54e082c85391'), ('http://127.0.0.1:8000/a1dba559990eff2402b6bde3a3af51091d688bd4', 'http://127.0.0.1:8000/a1dba559990eff2402b6bde3a3af51091d688bd4')], default='None', max_length=255, verbose_name='Random expiring url'),
        ),
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
