# Generated by Django 4.0.4 on 2022-05-20 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0050_alter_tiers_random_expiring_url_delete_uploadimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiers',
            name='random_expiring_url',
            field=models.CharField(choices=[('None', 'None'), ('http://127.0.0.1:8000/471400e249e5f149af7c91428052936c', 'http://127.0.0.1:8000/471400e249e5f149af7c91428052936c'), ('http://127.0.0.1:8000/8512c4d48fde3219496b0a19d70428e0055416ed', 'http://127.0.0.1:8000/8512c4d48fde3219496b0a19d70428e0055416ed')], default='None', max_length=255, verbose_name='Random expiring url'),
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/', verbose_name='Imagine origin url')),
                ('thumbnail_image', models.ImageField(upload_to=main.models.image_thumbnail_path, verbose_name='Imagine thumbnail')),
                ('thumbnail_image_two', models.ImageField(upload_to='img_thumbnail_two/', verbose_name='Imagine thumbnail two')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
        ),
    ]
