# Generated by Django 4.0.4 on 2022-05-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_alter_tiers_random_expiring_url_uploadimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiers',
            name='random_expiring_url',
            field=models.CharField(choices=[('None', 'None'), ('http://127.0.0.1:8000/d9357fdba4d6fdf5f7800b46dced461f', 'http://127.0.0.1:8000/d9357fdba4d6fdf5f7800b46dced461f'), ('http://127.0.0.1:8000/814c6ccc1082e246a62fbbe53f6a998944ad61b7', 'http://127.0.0.1:8000/814c6ccc1082e246a62fbbe53f6a998944ad61b7')], default='None', max_length=255, verbose_name='Random expiring url'),
        ),
    ]
