# Generated by Django 4.0.4 on 2022-05-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_alter_tiers_random_expiring_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiers',
            name='random_expiring_url',
            field=models.CharField(choices=[('None', 'None'), ('http://127.0.0.1:8000/3828394616ea2925240789f778d659c9', 'http://127.0.0.1:8000/3828394616ea2925240789f778d659c9'), ('http://127.0.0.1:8000/62ea7f118f0c0063d1f33ed9e902642cbe790cba', 'http://127.0.0.1:8000/62ea7f118f0c0063d1f33ed9e902642cbe790cba')], default='None', max_length=255, verbose_name='Random expiring url'),
        ),
    ]
