# Generated by Django 4.0.4 on 2022-05-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_alter_tiers_random_expiring_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiers',
            name='random_expiring_url',
            field=models.CharField(choices=[('None', 'None'), ('http://127.0.0.1:8000/07ff91c416a14da9ed1480d4bf1ee248', 'http://127.0.0.1:8000/07ff91c416a14da9ed1480d4bf1ee248'), ('http://127.0.0.1:8000/8199b9c9941620436a01913d1e23b6564237b98f', 'http://127.0.0.1:8000/8199b9c9941620436a01913d1e23b6564237b98f')], default='None', max_length=255, verbose_name='Random expiring url'),
        ),
    ]
