# Generated by Django 4.0.4 on 2022-05-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_alter_tiers_random_expiring_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiers',
            name='random_expiring_url',
            field=models.CharField(choices=[('None', 'None'), ('http://127.0.0.1:8000/204e15a004de00861f886b816d9671c0', 'http://127.0.0.1:8000/204e15a004de00861f886b816d9671c0'), ('http://127.0.0.1:8000/eb4cb49dd2f75b7aa5e2d733cc770c90bf9b95ef', 'http://127.0.0.1:8000/eb4cb49dd2f75b7aa5e2d733cc770c90bf9b95ef')], default='None', max_length=255, verbose_name='Random expiring url'),
        ),
    ]
