# Generated by Django 4.0.4 on 2022-05-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_alter_tiers_random_expiring_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiers',
            name='random_expiring_url',
            field=models.CharField(choices=[('None', 'None'), ('http://127.0.0.1:8000/d6dc9269f2f4b2f11b081f52cf8247f2', 'http://127.0.0.1:8000/d6dc9269f2f4b2f11b081f52cf8247f2'), ('http://127.0.0.1:8000/7477846504945f4b1c047413ae721a149f9139ab', 'http://127.0.0.1:8000/7477846504945f4b1c047413ae721a149f9139ab')], default='None', max_length=255, verbose_name='Random expiring url'),
        ),
    ]
