# Generated by Django 4.0.4 on 2022-05-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_alter_tiers_random_expiring_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiers',
            name='random_expiring_url',
            field=models.CharField(choices=[('None', 'None'), ('http://127.0.0.1:8000/9103bf3f86e61d59da929e057bbb62e6', 'http://127.0.0.1:8000/9103bf3f86e61d59da929e057bbb62e6'), ('http://127.0.0.1:8000/abd62b29126ef7077cc21d393caa2a6267a2899b', 'http://127.0.0.1:8000/abd62b29126ef7077cc21d393caa2a6267a2899b')], default='None', max_length=255, verbose_name='Random expiring url'),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='thumbnail_image',
            field=models.ImageField(upload_to='img_thumbnail/', verbose_name='Imagine thumbnail'),
        ),
    ]
