# Generated by Django 4.0.4 on 2022-05-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_alter_tiers_random_expiring_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiers',
            name='random_expiring_url',
            field=models.CharField(choices=[('None', 'None'), ('http://127.0.0.1:8000/43b0a7a8caae642ec3b58b2b91eb1bbe', 'http://127.0.0.1:8000/43b0a7a8caae642ec3b58b2b91eb1bbe'), ('http://127.0.0.1:8000/75625c61ea558be0ecc24b56533706a37758df1c', 'http://127.0.0.1:8000/75625c61ea558be0ecc24b56533706a37758df1c')], default='None', max_length=255, verbose_name='Random expiring url'),
        ),
    ]
